version: '3.8'

services:
  hdf45:
      build:
        context: hdf_image
        dockerfile: Dockerfile
      image: phaustin/h4h5:sep30
      container_name: h4h5
      volumes:
        - /ScratchSSD/docker/jovyan/work/sat_lib/hdftools/hdf:/home/jovyan/work/hdf
        - /ScratchSSD/docker/jovyan/work/sat_data:/home/jovyan/work/sat_data
        - /ScratchSSD/docker/jovyan/work/data_share:/home/jovyan/work/data_share
        - /ScratchSSD/docker/jovyan/work/sat_lib:/home/jovyan/work/sat_lib
