[build-system]
requires = [
    "setuptools >= 48",
    "wheel >= 0.29.0"
]
build-backend = 'setuptools.build_meta'

[project]
name = "sat_lib"
description = "eoas gradelib"
version = "0.1"
dependencies = [
    "pyhdf",
    "click"
]
[project.scripts]
read_modis_meta = "sat_lib.modis_meta:main"


