[build-system]
requires = [
    "setuptools >= 48",
    "wheel >= 0.29.0"
]
build-backend = 'setuptools.build_meta'

[project]
name = "sat_lib"
description = "a301 satellite code"
authors = [
  { name="Philip Austin", email="paustin@eoas.ubc.ca" },
]
version = "0.1"




